// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Nyasers
//
// scripts/derive-thirdparty.mts — THIRD_PARTY_NOTICES.md 生成（derive 的 thirdparty 任务）
//
// 为什么单独成模块：这份通知的"人工部分"（每个包为什么在包里、以什么形态进来）是一张
// 事实表，改它要动数据而不是改逻辑；许可全文又是一份独立文本。分开放，derive.mts 只负责调度。
//
// 语言：**产物是英文**——它与 NOTICE、Apache 全文同族，读者是拿到分发件的人（含要查证的
// 第三方）。本文件的注释仍是中文（给维护者看）。
//
// 边界（很重要）：
//   · 只列**内联进产物**的组件——它们的原始包与 LICENSE 都不在 zip 里，必须由我们代为声明。
//   · 随包 node_modules/ 的物化依赖树**不列**：那批各自带着 LICENSE 进包（pack.mts 的
//     复制不排除它们），合规靠保留原件，本文件只给一句指引。
//   · 版本一律取自 vendor/hana-app-sdk/source-manifest.json 的 packedVersion（宿主打包时
//     写死的那份），不手抄、不猜。
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { FileTask } from "./derive.mts";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const join = (...p: string[]) => path.join(ROOT, ...p);

/** 随包 SDK 的来源与版本（宿主打包产出；仓库内一份快照）。 */
const SDK_MANIFEST = "vendor/hana-app-sdk/source-manifest.json";
/** 随包 SDK 的持包目录（形态描述里点名用）。 */
const SDK_DIR = "vendor/hana-app-sdk";
const SOURCE_LINE = `Hana App Creator SDK shipped with the host (snapshot under \`${SDK_DIR}\`; see \`source-manifest.json\` in the same directory)`;

/** 内联组件的元信息（人工知识：为什么在包里、以什么形态进来的）。 */
interface InlinedComponent {
  name: string;
  purpose: string;
  form: string;
  copyright?: string;
}

/**
 * 只列**内联**的组件。判定依据是 src/ 里的实际 import 链：
 *   · plugin-sdk：app-shell.ts / settings.tsx 直接 import，经 rspack 内联进 dist/ui/*
 *   · plugin-components：settings.tsx 直接 import（连 settings.css）
 *   · app-sdk：runtime/main.ts import connectAppRuntime，内联进 dist/runtime/dsh-host.mjs
 *   · plugin-protocol：plugin-sdk 的 dependency，随它一起被打进产物
 * 顺序按依赖方向（底 → 上），与产物里的层次一致。
 */
const COMPONENTS: InlinedComponent[] = [
  {
    name: "@hana/plugin-protocol",
    purpose:
      "Message-protocol constants and types exchanged between the host and plugins (for example the theme-change notification `THEME_CHANGED`).",
    form: `devDependency (\`file:${SDK_DIR}/hana-plugin-protocol-0.0.0.tgz\`); inlined together with @hana/plugin-sdk — it has no entry point of its own in the distribution.`,
  },
  {
    name: "@hana/plugin-sdk",
    purpose:
      "Browser-side App shell surface: `hana.api.fetch` and `hana.api.url` (App-surface session credential injection and runtime proxy path tickets), plus the surface / theme / clipboard / storage faces.",
    form: `devDependency (\`file:${SDK_DIR}/hana-plugin-sdk-0.0.0.tgz\`), inlined at build time by rspack into \`dist/ui/app-shell.js\` and \`dist/ui/settings.js\`; no vendored copy is shipped separately.`,
  },
  {
    name: "@hana/plugin-components",
    purpose:
      "Host settings components (`@hana/plugin-components/settings` and its `settings.css`), so the settings surface matches the host.",
    form: `devDependency (\`file:${SDK_DIR}/hana-plugin-components-0.0.0.tgz\`), inlined by rspack into \`dist/ui/settings.js\`.`,
  },
  {
    name: "@hana/app-sdk",
    purpose:
      "The `connectAppRuntime()` client runtime for the managed runtime's private IPC (tasks / models / network.fetch / close).",
    form: `devDependency (\`file:${SDK_DIR}/hana-app-sdk.tgz\`), statically inlined by rspack into \`dist/runtime/dsh-host.mjs\`.`,
    copyright: "Copyright (c) 2026 Hana App SDK authors (SPDX headers in the source files)",
  },
];

/** 许可全文（从既有通知一次性提取的原文副本；不重打法律文本）。 */
function apacheText(): string {
  const p = join("scripts", "derive", "licenses", "apache-2.0.txt");
  if (!fs.existsSync(p)) throw new Error(`missing license text: ${path.relative(ROOT, p)} (should be carried by the repo)`);
  return fs.readFileSync(p, "utf8");
}

/** 读随包 SDK 的 packedVersion（宿主打包时写入，仓库内快照）。 */
function packedVersion(): string {
  const j = JSON.parse(fs.readFileSync(join(SDK_MANIFEST), "utf8"));
  const v = j && j.packedVersion;
  if (typeof v !== "string" || !v) throw new Error(`${SDK_MANIFEST} has no packedVersion`);
  return v;
}

/** 生成整份 THIRD_PARTY_NOTICES.md。 */
function render(): string {
  const version = packedVersion();
  const lines: string[] = [
    "# Third-Party Notices",
    "",
    "Third-party components distributed with dshana, and their license notices.",
    "The project's own license is in NOTICE (MPL-2.0).",
    "",
    "Generated by `node scripts/derive.mts thirdparty` — do not edit by hand. Versions are read",
    `from \`packedVersion\` in \`${SDK_MANIFEST}\`.`,
    "",
    "## Components inlined into the distribution",
    "",
    "These are inlined into `dist/` at build time. Their original packages and LICENSE files are",
    "**not shipped**, so their notices are reproduced here.",
    "",
  ];
  for (const c of COMPONENTS) {
    lines.push(`### ${c.name}`, "");
    lines.push(`- Version: ${version}`);
    lines.push(`- Purpose: ${c.purpose}`);
    lines.push(`- Form: ${c.form}`);
    lines.push(`- Source: ${SOURCE_LINE}`);
    lines.push("- License: Apache License 2.0 (full text below)");
    if (c.copyright) lines.push(`- Copyright: ${c.copyright}`);
    lines.push("");
  }
  lines.push(
    "## Components under the shipped `node_modules/`",
    "",
    "The materialized production dependency tree (`node_modules/`) ships with its own LICENSE and",
    "NOTICE files. Licenses and copyrights live in each package's directory; this file does not",
    "duplicate them.",
    "",
    "--------------------------------------------------------------------------------",
    "",
    apacheText().trimEnd(),
    "",
  );
  return lines.join("\n");
}

/** 任务：thirdparty —— 随包 SDK manifest → THIRD_PARTY_NOTICES.md。 */
export const thirdpartyTask: FileTask = {
  kind: "file",
  name: "thirdparty",
  about: "vendor/hana-app-sdk 的 packedVersion → THIRD_PARTY_NOTICES.md",
  plan: () => [{ rel: "THIRD_PARTY_NOTICES.md", content: render() }],
};
